CoreDemo/Controllers/CommentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace CoreDemo.Controllers
{
    public class CommentController : Controller
    {

        CommentManager cm = new CommentManager(new EfCommentRepository());


        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult AddCommentPartial()
        {
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult AddCommentPartial(Comment comment)
        {
            comment.CommentDate=DateTime.Parse(DateTime.Now.ToShortDateString());
            comment.CommentStatus = true;
            comment.BlogId = 5;
            cm.AddComment(comment);
            return PartialView();
        }
        public PartialViewResult CommentListByBlog(int id)
        {
          
            var values=cm.GetAllComment(id);
            return PartialView(values);
        }

        

    }



}

CoreDemo/Views/Comment/AddCommentPartial.cshtml
<div class="comment-top">
    <h4>Bir yorum ekleyin</h4>
    <div class="comment-bottom">
        <form asp-controller="Comment" asp-action="AddCommentPartial" method="post">
            <input class="form-control" type="text" name="CommentUserName" placeholder="Adınız Soyadınız" required="">  
            
            <input class="form-control" type="text" name="CommentTitle" placeholder="Konu" required="">

            <textarea class="form-control" name="CommentContent" placeholder="Yorumunuz..." required=""></textarea>
            <button type="submit" class="btn btn-primary submit">Yorum Yap</button>
        </form>
    </div>
</div>

CoreDemo/Views/Comment/CommentListByBlog.cshtml
@model IEnumerable<EntityLayer.Concrete.Comment>
<div class="comment-top">
    <h4>Yorumlar</h4>
    <div class="media">
        <img src="~/CoreBlogTema/web/images/t1.jpg" alt="" class="img-fluid" />
        <div class="media-body">
            <h5 class="mt-0">Joseph Goh</h5>
            <p>
                Lorem Ipsum convallis diam consequat magna vulputate malesuada. id dignissim sapien velit id felis ac cursus eros.
                Cras a ornare elit.
            </p>

            <div class="media mt-3">
                <a class="d-flex pr-3" href="#">
                    <img src="~/CoreBlogTema/web/images/t2.jpg" alt="" class="img-fluid" />
                </a>
                <div class="media-body">
                    <h5 class="mt-0">Richard Spark</h5>
                    <p>
                        Lorem Ipsum convallis diam consequat magna vulputate malesuada. id dignissim sapien velit id felis ac cursus eros.
                        Cras a ornare elit.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>